# Copyright (C) 2026 Mike O'Toole
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later
"""The README's screenshots must exist, and must not leak a real deployment.

Two failure modes this guards against, both of which are only visible to a
stranger reading the repository page:

1. A broken image. Screenshots are regenerated by hand from the demo instance,
   so a rename or a forgotten `git add` silently ships a README full of broken
   image icons. Nobody who edits the README notices, because GitHub renders the
   local copy fine right up until it is pushed.

2. A screenshot taken from a real instance. The whole point of
   `scripts/seed-demo.py` is that the pictures come from fabricated data. A
   maintainer in a hurry can point a camera at their own running Pullbackup and
   publish their hostnames, dataset paths and network layout. That cannot be
   detected by looking at a PNG in review, so pin the provenance in prose
   instead: the README must say the data is fabricated and point at the script,
   and every committed screenshot must live under docs/screenshots/.
"""

import re
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
README = REPOSITORY_ROOT / "README.md"
SCREENSHOTS = REPOSITORY_ROOT / "docs" / "screenshots"

# Both markdown `![](path)` and the inline HTML `<img src="path">` used for the
# two-column table. A guard that only understood markdown would go blind the
# moment someone reached for a table, which is exactly when they stop looking.
REFERENCE = re.compile(r'(?:!\[[^\]]*\]\(|<img[^>]*\bsrc=")(docs/screenshots/[^)"\s]+)')


def _referenced() -> set[str]:
    return set(REFERENCE.findall(README.read_text()))


def test_every_readme_screenshot_reference_resolves():
    referenced = _referenced()
    assert referenced, (
        "README.md references no screenshots at all. If the screenshots section "
        "was removed deliberately, delete this test with it."
    )
    missing = sorted(p for p in referenced if not (REPOSITORY_ROOT / p).is_file())
    assert not missing, (
        f"README.md references screenshots that do not exist: {missing}. "
        "Regenerate them with `python3 scripts/seed-demo.py` and re-capture, or "
        "fix the path. A broken image is only visible once it is pushed."
    )


# The 8-byte signature every PNG starts with, and the 12-byte terminal chunk
# every complete PNG ends with (length 0, type IEND, CRC).
PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
PNG_IEND = b"\x00\x00\x00\x00IEND\xaeB`\x82"


def test_every_referenced_screenshot_is_a_real_png():
    """`is_file()` is not enough: a truncated or half-written file is present
    but still renders as a broken image, which is the exact failure this module
    exists to prevent. A zero-byte PNG survives `git add` without complaint.

    Checking the signature alone is also not enough, and the distinction cost a
    review round: a half-written file keeps a perfectly valid 8-byte header, so
    a magic-only check passes exactly the truncation scenario it claims to
    stop. Verified — a real PNG cut to half its bytes sailed through. So assert
    the terminal IEND chunk as well; it is the last 12 bytes of a complete PNG,
    which means a file that stops early cannot have it.

    This is still not a decoder: a file with a valid header and IEND but
    corrupt IDAT in between would pass. Catching that needs a CRC walk, and the
    failure it guards against (an editor mangling the middle of a binary) is
    not one that has ever happened here. Truncation is.
    """
    broken = []
    for reference in sorted(_referenced()):
        path = REPOSITORY_ROOT / reference
        if not path.is_file():
            continue  # already reported by the resolution test
        data = path.read_bytes()
        if not data.startswith(PNG_MAGIC):
            broken.append(f"{reference} ({len(data)} bytes, bad signature)")
        elif not data.endswith(PNG_IEND):
            broken.append(f"{reference} ({len(data)} bytes, no IEND — truncated?)")
    assert not broken, (
        f"README.md references files that are not complete PNGs: {broken}. "
        "A present-but-truncated file passes an existence check and still "
        "ships a broken image."
    )


def test_committed_screenshots_are_all_used():
    """An orphan is a stale picture of an older UI, waiting to be re-added."""
    if not SCREENSHOTS.is_dir():
        return
    on_disk = {
        f"docs/screenshots/{p.name}" for p in SCREENSHOTS.iterdir() if p.suffix == ".png"
    }
    orphans = sorted(on_disk - _referenced())
    assert not orphans, (
        f"docs/screenshots/ holds files the README never shows: {orphans}. "
        "Either reference them or delete them; a stale screenshot of an older "
        "UI is worse than none."
    )


def test_the_readme_states_the_screenshots_are_fabricated():
    """The provenance claim is the only thing standing between a hurried
    maintainer and publishing their own hostnames. Pin it in prose."""
    text = README.read_text()
    assert "fabricated" in text, (
        "README.md must state that the screenshot data is fabricated. Without "
        "it there is nothing telling the next maintainer not to photograph "
        "their real instance."
    )
    assert "scripts/seed-demo.py" in text, (
        "README.md must point at scripts/seed-demo.py so the next person "
        "regenerates the screenshots from the demo instance rather than theirs."
    )


def test_no_screenshot_lives_outside_the_screenshots_directory():
    """Keeps the provenance rule enforceable: one directory to audit."""
    strays = sorted(
        str(p.relative_to(REPOSITORY_ROOT))
        for p in REPOSITORY_ROOT.glob("docs/*.png")
    )
    assert not strays, (
        f"screenshots must live in docs/screenshots/, found: {strays}"
    )
